# Generated by Django 3.1.1 on 2020-09-08 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyTrainedModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(blank=True, max_length=30)),
                ('model_id', models.CharField(blank=True, max_length=50)),
                ('model_accuracy', models.CharField(blank=True, max_length=30)),
                ('model_loss', models.CharField(blank=True, max_length=30)),
                ('model_status', models.CharField(blank=True, max_length=30)),
                ('model_check', models.BooleanField(blank=True)),
                ('model_epochs', models.IntegerField(blank=True)),
            ],
        ),
    ]
