# Generated by Django 3.1.1 on 2020-09-09 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200909_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mytrainedmodel',
            name='model_accuracy',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='mytrainedmodel',
            name='model_id',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='mytrainedmodel',
            name='model_loss',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
