# Generated by Django 3.1.1 on 2020-09-09 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200909_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mytrainedmodel',
            name='model_image',
            field=models.ImageField(default='', upload_to='images'),
            preserve_default=False,
        ),
    ]
