# Generated by Django 3.1.1 on 2020-09-10 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200910_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mytrainedmodel',
            name='model_image',
            field=models.ImageField(upload_to='templates/static/images'),
        ),
    ]
