# Generated by Django 3.1.1 on 2020-09-15 12:04

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_mytrainedmodel_model_dict'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='mytrainedmodel',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
