# Generated by Django 3.1.1 on 2020-09-17 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_mytrainedmodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mytrainedmodel',
            name='image',
            field=models.ImageField(upload_to='core/images/'),
        ),
    ]
